platform :ios, '7.0'

target 'Smile Weather' do

#pod 'SmileWeather', :path => "../"

pod 'SmileWeather', path => "https://github.com/liu044100/SmileWeather.git"

end

target 'SmileWeather-ExampleTests' do

end

